### ISSUE TITLE
Python-eccodes version numbering changed again, Travis is testing against an old version

### ISSUE THREAD

**Issue by stephenworsley** [SciTools/iris#3723]
Python-eccodes previously changed their version numbering convention which resulted in #3593 being necessary in order to keep Travis using the latest version. Recently, python-eccodes has changed their version numbering convention again (see https://anaconda.org/conda-forge/python-eccodes/files) so that the changes made in #3593 are now causing Travis to not install the latest version. In order to pick up the latest version again, the changes made in #3593 should be reverted.

**Comment by pp-mo** [comment]
AFAICT the problem here is *not* that the numbering system has changed.
It is that they have provided 2 builds for the _same_ "version" (2020.04.0) without incrementing the build number.  Which is simply a thing you must **_never_** do in a conda channel !!

E.G. the file "linux-64/python-eccodes-2020.04.0-py36hda16e5c_0.tar.bz2" dates to 2020-05-04 @14:25
And its lib/info/recipe.yaml has
```
package:
    name: python-eccodes
    version: 2020.04.0
source:
    sha256: b2589c1850d0906d5b22bf699c0977736a704ee35799e4ea618e253332793ac4
    url: https://github.com/ecmwf/eccodes-python/archive/2020.04.0.tar.gz
build:
    number: '0'
    string: py38h8790de6_0
```

The file "linux-64/python-eccodes-2020.04.0-py38h8790de6_0.tar.bz2" dates to 2020-05-04 @14:29
(5 minutes later !)
And it provides colliding info
```
package:
    name: python-eccodes
    version: 2020.04.0
source:
    sha256: b2589c1850d0906d5b22bf699c0977736a704ee35799e4ea618e253332793ac4
    url: https://github.com/ecmwf/eccodes-python/archive/2020.04.0.tar.gz
build:
    number: '0'
    string: py36hda16e5c_0
```
